### ISSUE TITLE
add section on loading shapefiles into PostgreSQL data source

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/basic-PyQGIS-lesson#1]

**Comment by andGarc** [comment]
I assume the PostgreSQL data source is a database with the PostGIS extension enabled in which case we can use `ogr2ogr`.

To load a shapefile to PostgreSQL the command would be:
```
ogr2ogr -f "PostgreSQL" "PG:host=localhost dbname=<dbname> user=<user> password=<password>" "/path/to/some_shapefile.shp" -lco GEOMETRY_NAME=the_geom -lco FID=gid -lco PRECISION=no -nlt PROMOTE_TO_MULTI -nln new_layername -overwrite
```

To load a geojson to PostgreSQL the command would be:
```
ogr2ogr -f "PostgreSQL" PG:"host=localhost dbname=<dbname> user=<user> password=<password>" "/path/to/filaname.geojson"
```

[More details](https://www.bostongis.com/PrinterFriendly.aspx?content_name=ogr_cheatsheet)

**Comment by qdread** [comment]
@andGarc thanks for looking into this stuff! Looks like this lesson would have to basically be written almost from scratch. If you are interested in doing that at some point, there is no reason why you'd have to start with this, if you think it would be better to just start from the beginning again.
